---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openclaw-agent
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw-agent
    app.kubernetes.io/component: route
  annotations:
    haproxy.router.openshift.io/timeout: 180s
spec:
  to:
    kind: Service
    name: openclaw-agent
  port:
    targetPort: http-web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
