apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw

resources:
  - 01-namespace.yaml
  - 02-openclaw-serviceaccount.yaml
  - 03-openclaw-storage.yaml
  - 04-openclaw-config.yaml
  # 04-openclaw-secrets.yaml — não versionado, aplique separadamente
  - 05-openclaw-deployment.yaml
  - 06-openclaw-service.yaml
  - 07-openclaw-route.yaml
  - 08-openclaw-web-config.yaml
